/* config.h generated by cmake */
#ifndef _CONFIG_H
#define _CONFIG_H
// #define USE_NETCDF3
#define USE_REGEX
#define USE_TIGGE
// #define USE_MYSQL
#define USE_IPOLATES 1
// #define USE_UDF
#define USE_OPENMP
// #define USE_PROJ4
// #define USE_WMO_VALIDATION
// #define DISABLE_TIMEZONE
// #define DISABLE_ALARM
#define USE_NAMES NCEP
// #define USE_G2CLIB
// #define USE_PNG
#define USE_JASPER
// #define USE_OPENJPEG
// #define MAKE_FTN_API
#define USE_AEC
#define BUILD_COMMENTS "stock build"
#define CC "/usr/bin/cc GNU"
#define FORTRAN "/usr/bin/f95 GNU"
#define CPPFLAGS "-g  -DGFORTRAN"
#define FFLAGS "-g -fbacktrace "
#endif
