#include "cnames.h"

const struct ParmTable parm_table_ecmwf_151[256] = {
      /* 0 */ {"var0", "undefined"},
      /* 1 */ {"var1", "undefined"},
      /* 2 */ {"var2", "undefined"},
      /* 3 */ {"var3", "undefined"},
      /* 4 */ {"var4", "undefined"},
      /* 5 */ {"var5", "undefined"},
      /* 6 */ {"var6", "undefined"},
      /* 7 */ {"var7", "undefined"},
      /* 8 */ {"var8", "undefined"},
      /* 9 */ {"var9", "undefined"},
      /* 10 */ {"var10", "undefined"},
      /* 11 */ {"var11", "undefined"},
      /* 12 */ {"var12", "undefined"},
      /* 13 */ {"var13", "undefined"},
      /* 14 */ {"var14", "undefined"},
      /* 15 */ {"var15", "undefined"},
      /* 16 */ {"var16", "undefined"},
      /* 17 */ {"var17", "undefined"},
      /* 18 */ {"var18", "undefined"},
      /* 19 */ {"var19", "undefined"},
      /* 20 */ {"var20", "undefined"},
      /* 21 */ {"var21", "undefined"},
      /* 22 */ {"var22", "undefined"},
      /* 23 */ {"var23", "undefined"},
      /* 24 */ {"var24", "undefined"},
      /* 25 */ {"var25", "undefined"},
      /* 26 */ {"var26", "undefined"},
      /* 27 */ {"var27", "undefined"},
      /* 28 */ {"var28", "undefined"},
      /* 29 */ {"var29", "undefined"},
      /* 30 */ {"var30", "undefined"},
      /* 31 */ {"var31", "undefined"},
      /* 32 */ {"var32", "undefined"},
      /* 33 */ {"var33", "undefined"},
      /* 34 */ {"var34", "undefined"},
      /* 35 */ {"var35", "undefined"},
      /* 36 */ {"var36", "undefined"},
      /* 37 */ {"var37", "undefined"},
      /* 38 */ {"var38", "undefined"},
      /* 39 */ {"var39", "undefined"},
      /* 40 */ {"var40", "undefined"},
      /* 41 */ {"var41", "undefined"},
      /* 42 */ {"var42", "undefined"},
      /* 43 */ {"var43", "undefined"},
      /* 44 */ {"var44", "undefined"},
      /* 45 */ {"var45", "undefined"},
      /* 46 */ {"var46", "undefined"},
      /* 47 */ {"var47", "undefined"},
      /* 48 */ {"var48", "undefined"},
      /* 49 */ {"var49", "undefined"},
      /* 50 */ {"var50", "undefined"},
      /* 51 */ {"var51", "undefined"},
      /* 52 */ {"var52", "undefined"},
      /* 53 */ {"var53", "undefined"},
      /* 54 */ {"var54", "undefined"},
      /* 55 */ {"var55", "undefined"},
      /* 56 */ {"var56", "undefined"},
      /* 57 */ {"var57", "undefined"},
      /* 58 */ {"var58", "undefined"},
      /* 59 */ {"var59", "undefined"},
      /* 60 */ {"var60", "undefined"},
      /* 61 */ {"var61", "undefined"},
      /* 62 */ {"var62", "undefined"},
      /* 63 */ {"var63", "undefined"},
      /* 64 */ {"var64", "undefined"},
      /* 65 */ {"var65", "undefined"},
      /* 66 */ {"var66", "undefined"},
      /* 67 */ {"var67", "undefined"},
      /* 68 */ {"var68", "undefined"},
      /* 69 */ {"var69", "undefined"},
      /* 70 */ {"var70", "undefined"},
      /* 71 */ {"var71", "undefined"},
      /* 72 */ {"var72", "undefined"},
      /* 73 */ {"var73", "undefined"},
      /* 74 */ {"var74", "undefined"},
      /* 75 */ {"var75", "undefined"},
      /* 76 */ {"var76", "undefined"},
      /* 77 */ {"var77", "undefined"},
      /* 78 */ {"var78", "undefined"},
      /* 79 */ {"var79", "undefined"},
      /* 80 */ {"var80", "undefined"},
      /* 81 */ {"var81", "undefined"},
      /* 82 */ {"var82", "undefined"},
      /* 83 */ {"var83", "undefined"},
      /* 84 */ {"var84", "undefined"},
      /* 85 */ {"var85", "undefined"},
      /* 86 */ {"var86", "undefined"},
      /* 87 */ {"var87", "undefined"},
      /* 88 */ {"var88", "undefined"},
      /* 89 */ {"var89", "undefined"},
      /* 90 */ {"var90", "undefined"},
      /* 91 */ {"var91", "undefined"},
      /* 92 */ {"var92", "undefined"},
      /* 93 */ {"var93", "undefined"},
      /* 94 */ {"var94", "undefined"},
      /* 95 */ {"var95", "undefined"},
      /* 96 */ {"var96", "undefined"},
      /* 97 */ {"var97", "undefined"},
      /* 98 */ {"var98", "undefined"},
      /* 99 */ {"var99", "undefined"},
      /* 100 */ {"var100", "undefined"},
      /* 101 */ {"var101", "undefined"},
      /* 102 */ {"var102", "undefined"},
      /* 103 */ {"var103", "undefined"},
      /* 104 */ {"var104", "undefined"},
      /* 105 */ {"var105", "undefined"},
      /* 106 */ {"var106", "undefined"},
      /* 107 */ {"var107", "undefined"},
      /* 108 */ {"var108", "undefined"},
      /* 109 */ {"var109", "undefined"},
      /* 110 */ {"var110", "undefined"},
      /* 111 */ {"var111", "undefined"},
      /* 112 */ {"var112", "undefined"},
      /* 113 */ {"var113", "undefined"},
      /* 114 */ {"var114", "undefined"},
      /* 115 */ {"var115", "undefined"},
      /* 116 */ {"var116", "undefined"},
      /* 117 */ {"var117", "undefined"},
      /* 118 */ {"var118", "undefined"},
      /* 119 */ {"var119", "undefined"},
      /* 120 */ {"var120", "undefined"},
      /* 121 */ {"var121", "undefined"},
      /* 122 */ {"var122", "undefined"},
      /* 123 */ {"var123", "undefined"},
      /* 124 */ {"var124", "undefined"},
      /* 125 */ {"var125", "undefined"},
      /* 126 */ {"var126", "undefined"},
      /* 127 */ {"var127", "undefined"},
      /* 128 */ {"var128", "In situ Temperature [deg C]"},
      /* 129 */ {"OCPT", "Ocean potential temperature [deg C]"},
      /* 130 */ {"S", "Salinity [psu]"},
      /* 131 */ {"OCU", "Ocean current zonal component [m s**-1]"},
      /* 132 */ {"OCV", "Ocean current meridional component [m s**-1]"},
      /* 133 */ {"OCW", "Ocean current vertical component [m s**-1]"},
      /* 134 */ {"MST", "Modulus of strain rate tensor [s**-1]"},
      /* 135 */ {"VVS", "Vertical viscosity [m**2 s**-1]"},
      /* 136 */ {"VDF", "Vertical diffusivity [m**2 s**-1]"},
      /* 137 */ {"DEP", "Bottom level Depth [m]"},
      /* 138 */ {"STH", "Sigma-theta [kg m**-3]"},
      /* 139 */ {"RN", "Richardson number []"},
      /* 140 */ {"UV", "UV product [m**2 s**-2]"},
      /* 141 */ {"UT", "UT product [m s**-1 degC]"},
      /* 142 */ {"VT", "VT product [m s**-1 deg C]"},
      /* 143 */ {"UU", "UU product [m**2 s**-2]"},
      /* 144 */ {"VV", "VV product [m**2 s**-2]"},
      /* 145 */ {"SL", "Sea level [m]"},
      /* 146 */ {"SL_1", "Sea level previous timestep [m]"},
      /* 147 */ {"BSF", "Barotropic stream function [m**3 s**-1]"},
      /* 148 */ {"MLD", "Mixed layer depth [m]"},
      /* 149 */ {"BTP", "Bottom Pressure (equivalent height) [m]"},
      /* 150 */ {"SH", "Steric height [m]"},
      /* 151 */ {"CRL", "Curl of Wind Stress [N m**-3]"},
      /* 152 */ {"var152", "Divergence of wind stress [Nm**-3]"},
      /* 153 */ {"TAX", "U stress [N m**-2]"},
      /* 154 */ {"TAY", "V stress [N m**-2]"},
      /* 155 */ {"TKI", "Turbulent kinetic energy input [W m**-2]"},
      /* 156 */ {"NSF", "Net surface heat flux [W m**-2]"},
      /* 157 */ {"ASR", "Absorbed solar radiation [W m**-2]"},
      /* 158 */ {"PME", "Precipitation - evaporation [m s**-1]"},
      /* 159 */ {"SST", "Specified sea surface temperature [deg C]"},
      /* 160 */ {"SHF", "Specified surface heat flux [W m**-2]"},
      /* 161 */ {"DTE", "Diagnosed sea surface temperature error [deg C]"},
      /* 162 */ {"HFC", "Heat flux correction [W m**-2]"},
      /* 163 */ {"20D", "20 degrees isotherm depth [m]"},
      /* 164 */ {"TAV300", "Average potential temperature in the upper 300m [degrees C]"},
      /* 165 */ {"UBA1", "Vertically integrated zonal velocity (previous time step) [m**2 s**-1]"},
      /* 166 */ {"VBA1", "Vertically Integrated meridional velocity (previous time step) [m**2 s**-1]"},
      /* 167 */ {"ZTR", "Vertically integrated zonal volume transport [m**2 s**-1]"},
      /* 168 */ {"MTR", "Vertically integrated meridional volume transport [m**2 s**-1]"},
      /* 169 */ {"ZHT", "Vertically integrated zonal heat transport [J m**-1 s**-1]"},
      /* 170 */ {"MHT", "Vertically integrated meridional heat transport [J m**-1 s**-1]"},
      /* 171 */ {"UMAX", "U velocity maximum [m s**-1]"},
      /* 172 */ {"DUMAX", "Depth of the velocity maximum [m]"},
      /* 173 */ {"SMAX", "Salinity maximum [psu]"},
      /* 174 */ {"DSMAX", "Depth of salinity maximum [m]"},
      /* 175 */ {"SAV300", "Average salinity in the upper 300m [psu]"},
      /* 176 */ {"LDP", "Layer Thickness at scalar points [m]"},
      /* 177 */ {"LDU", "Layer Thickness at vector points [m]"},
      /* 178 */ {"PTI", "Potential temperature increment [deg C]"},
      /* 179 */ {"PTAE", "Potential temperature analysis error [deg C]"},
      /* 180 */ {"BPT", "Background potential temperature [deg C]"},
      /* 181 */ {"APT", "Analysed potential temperature [deg C]"},
      /* 182 */ {"PTBE", "Potential temperature background error [deg C]"},
      /* 183 */ {"AS", "Analysed salinity [psu]"},
      /* 184 */ {"SALI", "Salinity increment [psu]"},
      /* 185 */ {"EBT", "Estimated Bias in Temperature [deg C]"},
      /* 186 */ {"EBS", "Estimated Bias in Salinity [psu]"},
      /* 187 */ {"UVI", "Zonal Velocity increment (from balance operator) [m/s per time step]"},
      /* 188 */ {"VVI", "Meridional Velocity increment (from balance operator) []"},
      /* 189 */ {"var189", "undefined"},
      /* 190 */ {"SUBI", "Salinity increment (from salinity data) [psu per time step]"},
      /* 191 */ {"SALE", "Salinity analysis error [psu]"},
      /* 192 */ {"BSAL", "Background Salinity [psu]"},
      /* 193 */ {"var193", "Reserved []"},
      /* 194 */ {"SALBE", "Salinity background error [psu]"},
      /* 195 */ {"var195", "undefined"},
      /* 196 */ {"var196", "undefined"},
      /* 197 */ {"var197", "undefined"},
      /* 198 */ {"var198", "undefined"},
      /* 199 */ {"EBTA", "Estimated temperature bias from assimilation [deg C]"},
      /* 200 */ {"EBSA", "Estimated salinity bias from assimilation [psu]"},
      /* 201 */ {"LTI", "Temperature increment from relaxation term [deg C per time step]"},
      /* 202 */ {"LSI", "Salinity increment from relaxation term []"},
      /* 203 */ {"BZPGA", "Bias in the zonal pressure gradient (applied) [Pa**m-1]"},
      /* 204 */ {"BMPGA", "Bias in the meridional pressure gradient (applied) [Pa**m-1]"},
      /* 205 */ {"EBTL", "Estimated temperature bias from relaxation [deg C]"},
      /* 206 */ {"EBSL", "Estimated salinity bias from relaxation [psu]"},
      /* 207 */ {"FGBT", "First guess bias in temperature [deg C]"},
      /* 208 */ {"FGBS", "First guess bias in salinity [psu]"},
      /* 209 */ {"BPA", "Applied bias in pressure [Pa]"},
      /* 210 */ {"FGBP", "FG bias in pressure [Pa]"},
      /* 211 */ {"PTA", "Bias in temperature(applied) [deg C]"},
      /* 212 */ {"PSA", "Bias in salinity (applied) [psu]"},
      /* 213 */ {"var213", "undefined"},
      /* 214 */ {"var214", "undefined"},
      /* 215 */ {"var215", "undefined"},
      /* 216 */ {"var216", "undefined"},
      /* 217 */ {"var217", "undefined"},
      /* 218 */ {"var218", "undefined"},
      /* 219 */ {"var219", "undefined"},
      /* 220 */ {"var220", "undefined"},
      /* 221 */ {"var221", "undefined"},
      /* 222 */ {"var222", "undefined"},
      /* 223 */ {"var223", "undefined"},
      /* 224 */ {"var224", "undefined"},
      /* 225 */ {"var225", "undefined"},
      /* 226 */ {"var226", "undefined"},
      /* 227 */ {"var227", "undefined"},
      /* 228 */ {"var228", "undefined"},
      /* 229 */ {"var229", "undefined"},
      /* 230 */ {"var230", "undefined"},
      /* 231 */ {"var231", "undefined"},
      /* 232 */ {"var232", "undefined"},
      /* 233 */ {"var233", "undefined"},
      /* 234 */ {"var234", "undefined"},
      /* 235 */ {"var235", "undefined"},
      /* 236 */ {"var236", "undefined"},
      /* 237 */ {"var237", "undefined"},
      /* 238 */ {"var238", "undefined"},
      /* 239 */ {"var239", "undefined"},
      /* 240 */ {"var240", "undefined"},
      /* 241 */ {"var241", "undefined"},
      /* 242 */ {"var242", "undefined"},
      /* 243 */ {"var243", "undefined"},
      /* 244 */ {"var244", "undefined"},
      /* 245 */ {"var245", "undefined"},
      /* 246 */ {"var246", "undefined"},
      /* 247 */ {"var247", "undefined"},
      /* 248 */ {"var248", "undefined"},
      /* 249 */ {"var249", "undefined"},
      /* 250 */ {"var250", "undefined"},
      /* 251 */ {"var251", "undefined"},
      /* 252 */ {"var252", "undefined"},
      /* 253 */ {"var253", "undefined"},
      /* 254 */ {"var254", "undefined"},
      /* 255 */ {"var255", " []"},
};
