/** @file
 * @brief Routines that write output to files.
 * 
 * ### Program History Log
 * Date | Programmer | Comments
 * -----|------------|---------
 * 2006 | W. Ebisuzaki | Initial
 * 01/2007 | M. Schwarb | Cleanup
 * 01/2008 | W. Ebisuzaki | lat and lon changed from float to double
 * 01/2008 | W. Ebisuzaki | Use filename "-" to write to stdout (-text, -spread)
 * 02/2008 | W. Ebisuzaki | Use filename "-" to write to stdout (-text, -spread) revised
 * 02/2008 | W. Ebisuzaki | Use filename "-" to write to stdout (-text, -spread) revised
 * 02/2008 | W. Ebisuzaki | Remove decode flags for grib, GRIB
 * 06/2011 | W. Ebisuzaki | WxText enabled -spread, added flush_mode to -spread
 *
 * @author Public Domain: Wesley Ebisuzaki @date 2006
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "wgrib2.h"
#include "fnlist.h"

/** File header flag. */
extern int header;

/** Append grib file flag. */
extern int file_append;

/** Decode grib file flag. */
extern int decode;

/** Flag to indicate lat-lon grid processing.  */
extern int latlon;

/** Flush of output flag. */
extern int flush_mode;

/** Number of grid points in the x-direction. */
extern int nx;

/** Number of grid points in the y-direction. */
extern int ny;

/** Pointer to array of latitude values. */
extern double *lat;

/** Pointer to array of longitude values. */
extern double *lon;

/** NDFD local section 2 keys. */
extern int WxText;

/**  Number of keys. */
extern int WxNum;

/* parameters for text mode */

/** Pointer to text format.*/
const char *text_format;

/** Number of columns in text output. */
int text_column;

/** Pointer to new line character. */
extern const char *nl;

/*
 * HEADER:100:bin:output:1:write binary data to X
 */

/**
 * Writes the grid values to a specified file in binary format  (C: float, Fortran: real)
 * 
 * The default order is WE:SN (see -order option) with f77 header/trailer (see -no_header). 
 * The undefined value is 9.999e20. The file format remains unchanged from wgrib except the 
 * order of grid points can now be specified. 
 * 
 * When the header flag is on (default, or by the option -header), , the header consists of 
 * an integer with the byte count of the data. The size of the integer (4 or 8 bytes) depends 
 * on the native size of the integer. Usually this size is compile time option. This is 
 * different from the f77 header which is generated by -ieee which is always a 4 byte integer. 
 * 
 * When the header flag if off (by the option -no_header), the binary grid points are written 
 * with no header. To read the data, you need to know the size of the grid. 
 * 
 * The default order of the grid point data is WE:SN. The order of the grid point data can be 
 * changed to raw and WE:NS by use of the -order option. 
 * 
 * On most machines, the binary format is either big or little-endian single precision IEEE. 
 * 
 * ## Usage
 * -bin file_name
 * 
 * "-" sends the output to the terminal/stdout (results are unpredicatable in Windows)
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * ## Example 
 * ???
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_bin(ARG1) {
    unsigned int i, j;
    struct seq_file *save;

    if (mode == -1) {
        *local = save = (struct seq_file *) malloc( sizeof(struct seq_file));
        if (save == NULL) fatal_error("bin: memory allocation","");
        if (fopen_file(save, arg1, file_append ? "ab" : "wb") != 0) {
            free(save);
            fatal_error("Could not open %s", arg1);
        }
        decode = 1;
    }
    else if (mode == -2) {
        save = *local;
        fclose_file(save);
        free(save);
    }
    else if (mode >= 0) {
        save = *local;
        if (header) {
            if (ndata > 4294967295U / sizeof(float))
                fatal_error("bin: 4-byte header overflow","");
            i = ndata * sizeof(float);
            j = fwrite_file((void *) &i, sizeof(int), 1, save);
            if (j != 1) fatal_error("bin: write header","");
        }
        j = fwrite_file((void *) data, sizeof(float), ndata, save);
        if (j != ndata) fatal_error_u("bin: error writing grid point written=%u", j);
        if (header) {
            i = ndata * sizeof(float);
            j = fwrite_file((void *) &i, sizeof(int),1, save);
            if (j != 1) fatal_error("bin: write header","");
        }
        if (flush_mode) fflush_file(save);
    }
    return 0;
}

/*
 * HEADER:100:ieee:output:1:write (default:big-endian) IEEE data to X
 */

/**
 * Writes the grid values to a specified file in IEEE format (C: float, Fortran: real)
 *
 * By default, the data are written out in WE:SN order (see -order option) with f77 
 * header/trailer (see -no_header option). The undefined value is 9.999e20. The output 
 * format is unchanged from wgrib except the order can now be specified.
 * 
 * The default is to write a 4 byte header and trailer with the record size in bytes. No 
 * header and trailer are written if the header flag is off by the -no_header option.
 * 
 * The default is write the grid point data in WE:SN order. The ordering of the data can 
 * be changed to raw or WE:NS by the -order option.
 * 
 * The default endian of the header, trailer and data are in big endian order. This can 
 * be changed to little endian by the -little_endian option.
 * 
 * The -ieee option is slower than the -bin option and may not be exact on an ieee machine 
 * because all grid point data is converted from the native format into ieee format by a 
 * software routine.
 *
 * ## Usage
 * -ieee file_name
 *
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 *
 * @return 0 for success, error code otherwise
 *
 * ## Example
 * ???
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_ieee(ARG1) {
    struct seq_file *save;

    if (mode == -1) {
        *local = save = (struct seq_file *) malloc( sizeof(struct seq_file));
        if (save == NULL) fatal_error("ieee: memory allocation","");
        if (fopen_file(save, arg1, file_append ? "ab" : "wb") != 0) {
            free(save);
            fatal_error("Could not open %s", arg1);
        }
        decode = 1;
    }
    else if (mode == -2) {
        save = *local;
        fclose_file(save);
        free(save);
    }
    else if (mode >= 0) {
        save = *local;
        wrtieee(data, ndata, header, save);
        if (flush_mode) fflush_file(save);
    }
    return 0;
}

/*
 * HEADER:100:text_fmt:misc:1:format for text output (C)
 */

/**
 * Set format for text output (C)
 * 
 * ## Usage
 * -text_fmt format
 * 
 * format is a printf format string, e.g., "%g" or "%10.3f"
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_text_fmt(ARG1) {
    if (mode >= -1) text_format = arg1;
    return 0;
}

/*
 * HEADER:100:text_col:misc:1:number of columns on text output
 */

/**
 * Wgrib2's -text and -ijbox options will/can write text files. The default is to write 
 * one number per line of output. By using -text_col option, you can write N numbers 
 * per line. 
 * 
 * ## Usage
 * -text_col N
 * 
 * N is an integer greater than zero
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * ## Example
 * ???
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_text_col(ARG1) {
    if (mode >= -1) {
        text_column = atoi(arg1);
        if (text_column < 1) text_column = 1;
    }
    return 0;
}

/*
 * HEADER:100:text:output:1:write text data into X
 */

/**
 * Writes the grid values to a specified file as a text (ascii) file.
 * 
 * The default format (-header) is (per decoded grib message)
 *      NX NY
 *      val-1
 *      val-2
 *      ...
 *      val-(NX*NY)
 * Where NX and NY are the dimension of the grid and val-N is the Nth grid point in 
 * WE:SN order. When the -no_header option is used, the format is 
 * 
 *      val-1
 *      val-2
 *      ...
 *      val-(NX*NY)
 * 
 * The default order of the data is WE:SN which differs from wgrib's order which is 
 * equivalent to the "-order raw" in wgrib2. Another difference is that wgrib's -text 
 * option requires a filename. The undefined value is 9.999e20. The format of the output 
 * is unchanged from wgrib except the order, number of columns and precision can be altered 
 * by the user. 
 * 
 * ## Usage
 * -text_fmt file_name
 * 
 * "-" sends the data to the terminal/stdout
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 *
 * ## Example
 * ???
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_text(ARG1) {
    unsigned int i;

    if (mode == -1) {
        if ((*local = (void *) ffopen(arg1,file_append ? "a" : "w")) == NULL) 
            fatal_error("Could not open %s", arg1);
        decode = 1;
    }
    else if (mode == -2) {
        ffclose((FILE *) *local);
        // free(*local);
    }
    else if (mode >= 0) {
        if (header == 1) {
            fprintf((FILE *) *local,"%d %d\n", nx, ny);
	    }
        for (i = 0; i < ndata; i++) {
            fprintf((FILE *) *local, text_format, data[i]);
            fprintf((FILE *) *local, ((i+1) % text_column) ? " " : "\n");
        }
        if (flush_mode) fflush((FILE *) *local);
    }
    return 0;
}

/*
 * HEADER:100:spread:output:1:write text - spread sheet format into X (WxText enabled)
 */

/**
 * Writes the grid values to a specified file as a comma separated values (text) which 
 * can be imported into a spread sheet. 
 * 
 *    lon,lat,(VARIABLE DESCRIPTION)
 *    lon-1,lat-1,val-1
 *    lon-2,lat-2,val-2
 *    ...
 *    lon-N,lat-N,val-N
 * 
 * The latitudes and longitudes are only available for supported grids and only the default 
 * WE:SN order is supported. The undefined value is 9.999e20. 
 * 
 * Use the -undefine option to limit the output to specified regions. 
 * 
 * ## Usage
 * -spread file_name
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 *
 * @note Warning #1: The options -csv, -csv_long, -spread and -text do not support memory files. 
 * You can blame sloth or lack of need. I like to think that text files with grid point values 
 * are are insanely large and shouldn't be saved in memory. 
 * 
 * @note Warning #2: It may be tempting to take a grib file, convert it into a CSV file and then 
 * deal with the CSV file. After all, everybody can read a CSV file. Sure there is a litte 
 * overhead of reading a CSV file but who cares. Suppose you want to read some GFS forecasts files 
 * (20 forecast times, 5 days every 6 hours) at 0.25 x 0.25 degree global resolution. Your CSV file 
 * is going to be about 720 GBs. Suppose that our hard drive can write/read at 70 MB/s. Then we are 
 * talking about 3 hours to write the CSV file and 3 hours to read the CSV file not including CPU time 
 * which will slow down the process. Converting grib into CSV is a viable strategy if the conversion is 
 * limited. You need to restrict the number of fields converted and should consider only converting a 
 * regional domain. Note, I wrote "viable" and not optimal. 
 * 
 * ## Example
 * ???
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_spread(ARG1) {
    unsigned int i;

    if (mode == -1) {
        if ((*local = (void *) ffopen(arg1,file_append ? "a" : "w")) == NULL)
            fatal_error("Could not open %s", arg1);
        WxText = latlon = decode = 1;
    }
    else if (mode == -2) {
        ffclose((FILE *) *local);
    }
    else if (mode >= 0) {
        if (lat == NULL || lon == NULL || data == NULL) {
            fprintf(stderr,"no code to determine lat-lon information, no spread sheet output\n");
            return 0;
        }
        set_mode(0);
        f_var(call_ARG0(inv_out,NULL));
        fprintf((FILE *) *local,"lon,lat,%s",inv_out);
        f_lev(call_ARG0(inv_out,NULL));
        fprintf((FILE *) *local," %s", inv_out);
        f_t(call_ARG0(inv_out,NULL));
        fprintf((FILE *) *local," %s", inv_out);
        f_ftime(call_ARG0(inv_out,NULL));
        fprintf((FILE *) *local," %s\n", inv_out);

        if (WxNum > 0) {
            for (i = 0; i < ndata; i++) {
                if(!UNDEFINED_VAL(data[i])) 
                    fprintf((FILE *) *local,"%lf,%lf,\"%s\"\n",lon[i],lat[i],WxLabel(data[i]));
            }
        }
        else {
            for (i = 0; i < ndata; i++) {
                if(!UNDEFINED_VAL(data[i])) 
                    fprintf((FILE *) *local,"%lf,%lf,%g\n",lon[i],lat[i],data[i]);
            }
        }
        if (flush_mode) fflush((FILE *) *local);
        inv_out[0] = 0;
        set_mode(mode);
    }

    return 0;
}

/*
 * HEADER:100:GRIB:output:1:writes entire GRIB record (all submessages)
 */

/**
 * Copies an entire GRIB2 message (including all the submessages) to a specified file.
 * 
 * This is useful if you want to preserve to keep the submessages. This is in contrast 
 * to the -grib option which writes submessages into its own grib message. 
 * 
 * The -GRIB option should only be used to copy the original grib message to another file. 
 * Unlike the the -grib option, changing the metadata is not recommended. 
 * 
 * ## Usage
 * -GRIB file_name
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_GRIB(ARG1) {
    size_t size;
    struct seq_file *save;

    if (mode == -1) {
        *local = save = (struct seq_file *) malloc( sizeof(struct seq_file));
        if (save == NULL) fatal_error("GRIB: memory allocation","");
        if (fopen_file(save, arg1, file_append ? "ab" : "wb") != 0) {
            free(save);
            fatal_error("Could not open %s", arg1);
        }
    }
    else if (mode == -2) {
        save = *local;
        fclose_file(save);
        free(save);
    }
    else if (mode >= 0) {
        save = *local;
        /* figure out size of grib file */
        size = uint8(sec[0]+8);
        /* write entire record to out */
        fwrite_file((void *) sec[0], sizeof(char), size, save);
        if (flush_mode) fflush_file(save);
    }
    return 0;
}

/*
 * HEADER:100:grib:output:1:writes GRIB record (one submessage) to X
 */

/**
 * Writes a GRIB record (one submessage) to a specified file in GRIB2 format.
 * 
 * This option only writes the current field (record/submessage) if the GRIB message 
 * contains multiple fields (records/submessages). If you want to copy the entire 
 * GRIB-2 message, use the -GRIB option. 
 * 
 * ## -grib vs. -grib_out
 * These two options do similar things, they write a grib message to a specified file. 
 * The -grib writes the grib message and -grib_out option takes the decoded grib message, 
 * converts it back into grib2 and then writes it out. Obviously the latter option is much 
 * slower. You only use -grib_out when you have modified the data (grid) values. For example, 
 * you may have set many of the points to undefined in order to the data volume. Since the 
 * data values have changed, you have to use the -grib_out in order to create the smaller 
 * grib file. 
 * 
 * ## Usage
 * -grib file_name
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_grib(ARG1) {
    int i;
    struct seq_file *save;

    i = 0;
    if (mode == -1) {
        *local = save = (struct seq_file *) malloc( sizeof(struct seq_file));
        if (save == NULL) fatal_error("grib: memory allocation","");

        if (fopen_file(save, arg1, file_append ? "ab" : "wb") != 0) {
            free(save);
            fatal_error("Could not open %s", arg1);
        }
    }
    else if (mode == -2) {
        save = (struct seq_file *) *local;
        fclose_file(save);
        free(save);
    }
    else if (mode >= 0) {
        save = (struct seq_file *) *local;
        i = wrt_sec(sec[0], sec[1], sec[2], sec[3], sec[4], sec[5], sec[6],
                    sec[7], save);
        if (flush_mode) fflush_file(save);
    }
    return i;
}

/*
 * HEADER:100:persistent:setup:1:makes file X persistent if already opened (default on open), CW2
 *   only useful when wgrib is called as a subroutine, no error if failure
 */

/**
 * Marks an already open file as persistent. 
 * 
 * If a file is marked as persistent, the file will closed when the system terminates the program. 
 * If you run the wgrib2 utility, it makes no difference who closes the files. However, when you 
 * use the C/Fortran API, it makes a major difference. When you write C/Fortran programs that calls 
 * the wgrib2 API, you may want to use the same file thousands of times. It is better to open the 
 * file once rather than thousands of times. 
 * 
 * When opening a file, the default is to mark the file as persistent. 
 * 
 * ## Usage
 * -persistent FILE
 * 
 * FILE must be already opened.
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_persistent(ARG1) {
    if (mode == -1) {
        mk_file_persistent(arg1);
    }
    return 0;
}

/*
 * HEADER:100:transient:setup:1:make file X transient, CW2
 *   only useful when wgrib is called as a subroutine, no error if failure
 */

/**
 * Marks an already open file as transient.
 * 
 * If a file is marked as transient, wgrib2 will close the file as part of its normal 
 * "finalize" procedure.  If you run the wgrib2 utility, it makes no difference who 
 * closes the files. However, when you use the C/Fortran API, it makes a major difference. 
 * When you write C/Fortran programs that calls the wgrib2 API, you may want to use the 
 * same file thousands of times.
 * 
 * When opening a file, the default is to mark the file as persistent. 
 * 
 * ## Usage
 * -transient FILE
 * 
 * FILE must be already opened.
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_transient(ARG1) {
    if (mode == -1) {
        mk_file_transient(arg1);
    }
    return 0;
}

/*
 * HEADER:100:rewind_init:setup:1:rewinds file X on initialization if already opened, CW2
 *   only useful when wgrib is called as a subroutine, no error if failure
 */

/**
 * Rewinds an already open file in the setup or pre-processing phase. It is commonly 
 * used to rewind the inventory when searching from matching records.
 * 
 * This command is only useful in callable wgrib2
 * 
 * The wgrib2 library can either close or not close the files after calls to the 
 * wgrib2 subroutine. Closing the file frees up resources and helps prevent you 
 * from getting the "Too Many Files Open" error message. However, reopening files 
 * is a slow operation and you usually keep the files open if you plan to read/write 
 * to the file again. 
 * 
 * If you are reading from a previously opened and not-closed file, you will normally 
 * continue reading from where the last call to the wgrib2 subroutine stopped. Sometimes 
 * this is the preferred behavior. Sometimes, you want the library to start reading the 
 * file from the beginning. 
 * 
 * ## Usage
 * -rewind_init FILE
 * FILE must be already opened
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_rewind_init(ARG1) {
    int i;
    if (mode == -1) {
        i = rewind_file(arg1);
        if (i) fprintf(stderr,"WARNING: -rewind_init failed on %s\n", arg1);
    }
    return 0;
}

/*
 * HEADER:100:rewind_proc:misc:1:rewinds file X on processing step if already opened, CW2
 *   only useful when wgrib is called as a subroutine, no error if failure
 */

/**
 * Rewinds an already open file during the processing phase. 
 * 
 * This command is only useful in callable wgrib2
 * 
 * The wgrib2 library can either close or not close the files after calls to the 
 * wgrib2 subroutine. Closing the file frees up resources and helps prevent you 
 * from getting the "Too Many Files Open" error message. However, reopening files 
 * is a slow operation and you usually keep the files open if you plan to read/write 
 * to the file again. 
 * 
 * If you are reading from a previously opened and not-closed file, you will normally 
 * continue reading from where the last call to the wgrib2 subroutine stopped. Sometimes 
 * this is the preferred behavior. Sometimes, you want the library to start reading the 
 * file from the beginning. 
 * 
 * ## Usage
 * -rewind_proc FILE
 * FILE must be already opened
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_rewind_proc(ARG1) {
    int i;
    if (mode >= 0) {
        i = rewind_file(arg1);
        if (i) fprintf(stderr,"WARNING: -rewind failed on %s\n", arg1);
        return i;
    }
    return 0;
}

/*
 * HEADER:100:rewind_final:misc:1:rewinds file X on cleanup step if already opened, CW2
 *   only useful when wgrib is called as a subroutine, no error if failure
 */
/**
 * Rewinds an already open file in the final or after-all-processing phase. It is commonly 
 * used rewind the inventory when searching from matching records. 
 * 
 * This command is only useful in callable wgrib2
 * 
 * The wgrib2 library can either close or not close the files after calls to the 
 * wgrib2 subroutine. Closing the file frees up resources and helps prevent you 
 * from getting the "Too Many Files Open" error message. However, reopening files 
 * is a slow operation and you usually keep the files open if you plan to read/write 
 * to the file again. 
 * 
 * If you are reading from a previously opened and not-closed file, you will normally 
 * continue reading from where the last call to the wgrib2 subroutine stopped. Sometimes 
 * this is the preferred behavior. Sometimes, you want the library to start reading the 
 * file from the beginning. 
 * 
 * ## Usage
 * -rewind_final FILE
 * FILE must be already opened
 * 
 * @param ARG1 List of function arguments set by wgrib2's main() function (see @ref ARG1). These arguments 
 * won't be relevant to the average wgrib2 user. See the Usage section above for details about any input 
 * parameters.
 * 
 * @return 0 for success, error code otherwise
 * 
 * @author Wesley Ebisuzaki @date 2006
 */
int f_rewind_final(ARG1) {
    int i;
    if (mode == -2) {
        i = rewind_file(arg1);
        if (i) fprintf(stderr,"WARNING: -rewind failed on %s\n", arg1);
        return i;
    }
    return 0;
}
