# This is the Intel workflow for the wgrib2 project. This
# tests with Intel Classic and oneAPI.
#
# Alex Richert, 22 Oct 2024
name: Intel
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Linux_options:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compilers: ["oneapi", "classic"]
          
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config \
          libpng-dev zlib1g-dev libjpeg-dev autotools-dev autoconf libaec-dev \
          libopenblas-serial-dev libopenjp2-7 libopenjp2-7-dev

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        compiler-setup: ${{ matrix.compilers }}

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        jasper-version: version-4.0.0
        ip-version: develop
        g2c-version: develop
        g2c-cmake-args: -DUSE_OpenJPEG=ON -DUSE_Jasper=OFF

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: wgrib2

    - name: build
      run: |
        cd wgrib2
        mkdir b
        cd b
        cmake -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-ip;$GITHUB_WORKSPACE/nceplibs/jasper;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2c" .. -DMAKE_FTN_API=ON -DUSE_NETCDF=ON -DUSE_AEC=ON -DUSE_IPOLATES=ON -DUSE_OPENJPEG=ON -DUSE_PNG=ON
        make VERBOSE=1
    
    - name: test
      run: |
        ulimit -s unlimited
        ctest --verbose --output-on-failure --rerun-failed
