# This is a GitHub actions workflow for wgrib2.
#
# This builds the develop branch on MacOS.
#
# Alyson Stahl, 2/11/2025
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-13
    strategy:
      fail-fast: false
      matrix:
        ccompiler: [gcc, clang]
        sharedlib: [ON, OFF]
        jasper: [ON, OFF]
        openjpeg: [ON, OFF]
        exclude:
          - jasper: ON
            openjpeg: ON
          - jasper: OFF
            openjpeg: OFF

    steps:
    - name: install-dependencies
      run: |
        find /Library/Frameworks/ -name "png*"
        sudo rm -rf /Library/Frameworks/Mono.framework
        brew install jasper libpng jpeg-turbo openjpeg libaec libomp

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        g2c-version: develop
        g2c-cmake-args: -DUSE_OpenJPEG=${{matrix.openjpeg}} -DUSE_Jasper=${{matrix.jasper}}
        ip-version: develop

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: wgrib2

    - name: build
      run: |
        cd wgrib2
        mkdir build
        cd build
        #export CFLAGS='-I/Users/runner/work/wgrib2/wgrib2/nceplibs/NCEPLIBS-g2c/include'
        cmake -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/jasper;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2c;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-ip" .. -DUSE_AEC=ON -DUSE_G2CLIB_LOW=ON -DBUILD_SHARED_LIB=${{matrix.sharedlib}} -DMAKE_FTN_API=ON
        make VERBOSE=1
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/wgrib2/build
        ctest --verbose --output-on-failure --rerun-failed